apiVersion: apps/v1
kind: Deployment
metadata:
  name: ahmed
spec:
  selector:
    matchLabels:
      app: Mohammed
  replicas: 3
  template:
    metadata:
      name: first-pod
      labels:
        app: Mohammed
    spec:
      containers:
        - name: my-nginx-app
          image: ahmedesmael/os-test2
          imagePullPolicy: IfNotPresent #this will download the image only if it isn't in local images and it will not check if the images has updates or not (wont connect to the dockerhub)
          ports:
          - containerPort: 80
